services:
  finance-bot:
    build: .
    container_name: finance-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./credentials.json:/app/credentials.json
      - ./gmail_token.json:/app/gmail_token.json
      - ./client_secret.json:/app/client_secret.json
    environment:
      - TZ=Europe/Moscow
